services:
    f1bot:
        build:
            context: "."
        image: "${DOCKER_IMAGE:-ghcr.io/recursivegecko/race_bot:master}"
        environment:
            - DATABASE_PATH=/data/f1bot.db
            - PHX_SERVER="true"
            - PORT=4000
        ports:
            - "${DOCKER_BIND_PORT:-4000}:4000"
        env_file: .env
        restart: unless-stopped
        container_name: "${DOCKER_CONTAINER_NAME:-f1bot}"
        volumes:
            - "${DOCKER_DATA_VOLUME:-data}:/data"
volumes:
    data:
