services:
    f1bot:
        build:
            context: "."
        image: ghcr.io/recursivegecko/race_bot:master
        environment:
            - DATABASE_PATH=/data/f1bot.db
            - PHX_SERVER="true"
            - PORT=4000
        ports:
            - "4000:4000"
        env_file: .env
        restart: unless-stopped
        container_name: "f1bot"
        volumes:
            - data:/data
volumes:
    data:
